name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - run: |
          gpg \
            --quiet --batch --yes --decrypt --passphrase="${{ secrets.CLASP_PASSPHRASE }}" \
            --output $HOME/.clasprc.json .clasprc.json.gpg
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Apps Script
        run: npx clasp push
        env:
          CLASP_TOKEN_DIR: ${{ github.workspace }}
          CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
